sonar.projectKey=Amodamendis_Greenhouse-management-Web-tier
sonar.organization=amodamendis

# Scan the React source code
sonar.sources=src

# Ignore Vite build folders and node modules
sonar.exclusions=**/node_modules/**, dist/**